name: Generate Sitemap
on:
  push:
    branches:
      - main 
  workflow_dispatch: 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate the sitemap.xml
        uses: cicirello/generate-sitemap@v1
        with:
          base-url-path: https://dengodematen.github.io/
          include-html: true 
          additional-extensions: json

      - name: Commit and Push sitemap.xml
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "41898282+github-actions[bot].users.noreply.github.com"
          git add sitemap.xml
          git commit -m "chore: Generate sitemap.xml" || echo "No changes to sitemap.xml"
          git push
